name: main
on:
  push:
  
jobs: 
  job1:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo hello > world.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: world.txt
